# Generated by Django 4.2.10 on 2026-04-08 04:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fl_core', '0002_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientupdate',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Passed validation during aggregation'),
        ),
        migrations.AddField(
            model_name='clientupdate',
            name='validation_error',
            field=models.TextField(blank=True, help_text='Validation error details if failed', null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Token expiration time'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_data',
            field=models.BinaryField(blank=True, help_text='Serialized model weights (state_dict)', null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='aggregated_model_version',
            field=models.ForeignKey(blank=True, help_text="Model version created from this round's aggregation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregated_rounds', to='fl_core.modelversion'),
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='weight_delta',
            field=models.BinaryField(help_text='Serialized FULL model weights (state_dict) from client local training'),
        ),
        migrations.AlterField(
            model_name='round',
            name='model_version',
            field=models.ForeignKey(help_text='Initial model for this round', on_delete=django.db.models.deletion.PROTECT, to='fl_core.modelversion'),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('aggregated', 'Aggregated'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
