# Generated by Django 4.2.10 on 2026-05-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_core', '0003_clientupdate_is_valid_clientupdate_validation_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hardware_id',
            field=models.CharField(blank=True, help_text='Unique hardware ID (Android ID or iOS Vendor ID)', max_length=255, null=True, unique=True),
        ),
    ]
