# Generated by Django 5.1.14 on 2026-05-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_core', '0004_device_hardware_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('validated', 'Validated'), ('aggregated', 'Aggregated'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='app_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_version',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='version',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('aggregated', 'Aggregated'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
