web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120
worker: celery -A config worker -l info --concurrency 4
beat: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
release: python manage.py migrate && python manage.py collectstatic --noinput
