# Generated by Django 4.2.10 on 2026-04-05 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('app_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(upload_to='models/')),
                ('onnx_file', models.FileField(blank=True, null=True, upload_to='models/onnx/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('min_clients', models.IntegerField(default=3)),
                ('max_clients', models.IntegerField(default=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('aggregation_status', models.CharField(default='pending', help_text='pending, in_progress, completed, failed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fl_core.modelversion')),
            ],
            options={
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='RoundMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clients', models.IntegerField(default=0)),
                ('participating_clients', models.IntegerField(default=0)),
                ('avg_local_loss', models.FloatField(blank=True, null=True)),
                ('avg_local_accuracy', models.FloatField(blank=True, null=True)),
                ('global_loss', models.FloatField(blank=True, null=True)),
                ('global_accuracy', models.FloatField(blank=True, null=True)),
                ('aggregation_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='fl_core.round')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='fl_core.device')),
            ],
        ),
        migrations.CreateModel(
            name='ClientUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('num_examples', models.IntegerField()),
                ('local_loss', models.FloatField(blank=True, null=True)),
                ('local_accuracy', models.FloatField(blank=True, null=True)),
                ('weight_delta', models.BinaryField(help_text='Serialized weight delta or gradients')),
                ('parameters_hash', models.CharField(help_text='SHA256 hash of parameters', max_length=64)),
                ('dp_clip_norm', models.FloatField(blank=True, null=True)),
                ('dp_noise_scale', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('validated', 'Validated'), ('aggregated', 'Aggregated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='fl_core.device')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_updates', to='fl_core.round')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('device', 'round')},
            },
        ),
    ]
